IF NOT DEFINED ISEE_DASH_ROOT (SET ISEE_DASH_ROOT=D:\Dominic\GLAM\ISEE_DASH\DASHBOARDS\ISEE)
IF NOT DEFINED ISEE_DASH_PYENV (SET ISEE_DASH_PYENV=streamlit)
IF NOT DEFINED CONDA_PATH (SET CONDA_PATH="C:\Users\TheriaultD\AppData\Local\anaconda3\condabin\conda.bat")
IF NOT DEFINED ISEE_DASH_DATA (SET ISEE_DASH_DATA=P:\GLAM\Dashboard\ISEE_Dash_portable)

cd %ISEE_DASH_ROOT%

call %CONDA_PATH% activate %ISEE_DASH_PYENV%

streamlit run ISEE_DASH_0_1.py

timeout /t -1